(() => {
  const VALIDATE_URL='https://pa.wallissonghost.workers.dev/api/licenses/validate',STORAGE_KEY='not_license_key',DEVICE_KEY='not_device_id',REVALIDATE_MS=60*1000,NETWORK_GRACE_MS=3*60*1000;
  let revalidateTimer=null,graceTimer=null,lastConfirmedAt=0,nextValidationAt=0,sessionToken=null,sessionExpiresAt=0;
  const emit=(type,detail={})=>window.dispatchEvent(new CustomEvent('not-security-state',{detail:{type,at:Date.now(),...detail}}));
  function makeDeviceId(){const b=new Uint8Array(24);crypto.getRandomValues(b);return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('')}
  function getDeviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id||!/^[A-Za-z0-9_-]{16,128}$/.test(id)){id=makeDeviceId();localStorage.setItem(DEVICE_KEY,id)}return id}
  const deviceId=getDeviceId(),overlay=document.createElement('div');overlay.id='notLicenseGate';overlay.innerHTML=`<div class="not-license-card"><div class="not-license-brand">NOT / ACESSO</div><h1>Licença necessária</h1><p>Digite a chave privada gerada no painel Pa para liberar este jogo.</p><input id="notLicenseInput" type="password" autocomplete="off" autocapitalize="characters" spellcheck="false" placeholder="NOT-XXXX-XXXX-XXXX-XXXX-XXXX" /><button id="notLicenseButton" type="button">Validar chave</button><div id="notLicenseMessage">Aguardando uma licença válida.</div></div>`;document.body.appendChild(overlay);
  const input=overlay.querySelector('#notLicenseInput'),button=overlay.querySelector('#notLicenseButton'),message=overlay.querySelector('#notLicenseMessage');
  function showGate(t){if(!document.body.contains(overlay))document.body.appendChild(overlay);if(t)message.textContent=t}
  function publish(s){window.NOT_LICENSE=Object.freeze(s)}publish({authorized:false,status:'LOCKED'});
  function blockedMessage(r){return({DEVICE_LIMIT_REACHED:'Limite de dispositivos atingido para esta assinatura.',INVALID_DEVICE:'Este dispositivo não pôde ser identificado.',EXPIRED:'Assinatura expirada.',SUSPENDED:'Assinatura suspensa.',REVOKED:'Assinatura revogada.',TOO_MANY_ATTEMPTS:'Muitas tentativas. Aguarde e tente novamente.',INVALID_KEY:'Chave inválida.',SESSION_REQUIRED:'Sessão de licença inválida.'}[r]||'Licença não autorizada.')}
  function stopTimers(){if(revalidateTimer)clearInterval(revalidateTimer);if(graceTimer)clearTimeout(graceTimer);revalidateTimer=graceTimer=null;nextValidationAt=0}
  function lock(reason,removeKey=false){stopTimers();sessionToken=null;sessionExpiresAt=0;if(removeKey)localStorage.removeItem(STORAGE_KEY);publish({authorized:false,status:'LOCKED',reason});showGate(`Acesso bloqueado: ${blockedMessage(reason)}`);emit('license-locked',{reason,hasSession:false});window.dispatchEvent(new CustomEvent('not-license-locked',{detail:window.NOT_LICENSE}))}
  function setAuthorized(data,key){if(!data.sessionToken||!data.sessionExpiresAt)return lock('SESSION_REQUIRED');lastConfirmedAt=Date.now();nextValidationAt=lastConfirmedAt+REVALIDATE_MS;sessionToken=data.sessionToken;sessionExpiresAt=Date.parse(data.sessionExpiresAt)||0;if(graceTimer)clearTimeout(graceTimer);graceTimer=null;publish({authorized:true,status:'AUTHORIZED',plan:data.plan,expiresAt:data.expiresAt,deviceLimit:data.deviceLimit,activeDevices:data.activeDevices,lastConfirmedAt,sessionExpiresAt:data.sessionExpiresAt});localStorage.setItem(STORAGE_KEY,key);overlay.remove();emit('license-authorized',{hasSession:true,lastConfirmedAt,nextValidationAt,sessionExpiresAt});window.dispatchEvent(new CustomEvent('not-license-authorized',{detail:window.NOT_LICENSE}));if(!revalidateTimer)revalidateTimer=setInterval(()=>revalidate(key),REVALIDATE_MS)}
  function enterGrace(key){if(!sessionToken)return lock('VALIDATION_UNAVAILABLE');publish({...window.NOT_LICENSE,authorized:true,status:'GRACE_PERIOD',graceUntil:Date.now()+NETWORK_GRACE_MS});emit('license-grace',{hasSession:true,graceUntil:Date.now()+NETWORK_GRACE_MS});window.dispatchEvent(new CustomEvent('not-license-grace',{detail:window.NOT_LICENSE}));if(graceTimer)clearTimeout(graceTimer);graceTimer=setTimeout(async()=>{const ok=await revalidate(key,true);if(!ok&&window.NOT_LICENSE?.status==='GRACE_PERIOD')lock('VALIDATION_UNAVAILABLE')},NETWORK_GRACE_MS)}
  async function requestValidation(key){emit('validation-start',{hasSession:!!sessionToken});const res=await fetch(VALIDATE_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,deviceId}),cache:'no-store'}),data=await res.json().catch(()=>({}));return{res,data}}
  async function revalidate(rawKey,finalGraceCheck=false){const key=String(rawKey||'').trim().toUpperCase();if(!key){lock('INVALID_KEY',true);return false}try{const{res,data}=await requestValidation(key);if(!res.ok||!data.authorized){lock(data.reason||data.status||'INVALID_KEY',true);return false}setAuthorized(data,key);return true}catch{if(finalGraceCheck)return false;enterGrace(key);return false}}
  async function validate(rawKey,silent=false){const key=String(rawKey||'').trim().toUpperCase();if(!key)return;button.disabled=true;if(!silent)message.textContent='Validando…';try{const{res,data}=await requestValidation(key);if(!res.ok||!data.authorized){lock(data.reason||data.status||'INVALID_KEY',true);return}setAuthorized(data,key)}catch{lock('VALIDATION_UNAVAILABLE')}finally{button.disabled=false}}
  button.addEventListener('click',()=>validate(input.value));input.addEventListener('keydown',e=>{if(e.key==='Enter')validate(input.value)});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&sessionToken&&Date.now()-lastConfirmedAt>=REVALIDATE_MS)revalidate(localStorage.getItem(STORAGE_KEY))});window.addEventListener('online',()=>{if(window.NOT_LICENSE?.status==='GRACE_PERIOD')revalidate(localStorage.getItem(STORAGE_KEY))});
  Object.defineProperty(window,'NOT_LICENSE_SESSION',{configurable:false,enumerable:false,value:Object.freeze({getToken:()=>sessionToken&&Date.now()<sessionExpiresAt?sessionToken:null,getDeviceId:()=>deviceId,getSessionExpiresAt:()=>sessionExpiresAt,getNextValidationAt:()=>nextValidationAt,getLastConfirmedAt:()=>lastConfirmedAt})});
  setInterval(()=>emit('tick',{hasSession:!!(sessionToken&&Date.now()<sessionExpiresAt),nextValidationAt,lastConfirmedAt,sessionExpiresAt,status:window.NOT_LICENSE?.status||'LOCKED'}),250);
  const saved=localStorage.getItem(STORAGE_KEY);if(saved){input.value=saved;validate(saved,true)}
})();